@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion
title N.I.N.A. AI Cortex v5.0 - Backend Server

echo.
echo [96m============================================================[0m
echo [96m  N.I.N.A. AI Cortex v5.0 - Backend Server[0m
echo [96m  with OpenTelemetry Distributed Tracing[0m
echo [96m============================================================[0m
echo.

:: Переход в директорию скрипта
cd /d "%~dp0"

:: ============================================================
:: ПРОВЕРКА PYTHON
:: ============================================================
echo [93m[1/7][0m Checking Python installation...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [91m[ERROR][0m Python not found in PATH!
    echo Please install Python 3.12+ from https://python.org
    pause
    exit /b 1
)
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo    [92m[OK][0m Python %PYTHON_VERSION% found.

:: ============================================================
:: ПРОВЕРКА ВИРТУАЛЬНОГО ОКРУЖЕНИЯ
:: ============================================================
echo [93m[2/7][0m Checking virtual environment...
if not exist "venv\Scripts\activate.bat" (
    echo    [91m[ERROR][0m Virtual environment not found!
    echo    Creating new virtual environment...
    python -m venv venv
    if !errorlevel! neq 0 (
        echo [91m[ERROR][0m Failed to create virtual environment!
        pause
        exit /b 1
    )
    echo    [92m[OK][0m Virtual environment created.
) else (
    echo    [92m[OK][0m Virtual environment found.
)

:: Активация
call venv\Scripts\activate.bat

:: ============================================================
:: УСТАНОВКА ЗАВИСИМОСТЕЙ (включая OpenTelemetry)
:: ИСПРАВЛЕНО: убрана проблемная python -c проверка
:: ============================================================
echo [93m[3/7][0m Checking Python dependencies...

:: Проверяем через pip show (безопаснее чем python -c)
pip show opentelemetry-api >nul 2>&1
set OTEL_CHECK=!errorlevel!

if !OTEL_CHECK! neq 0 (
    echo    [93m[INFO][0m OpenTelemetry not installed. Installing dependencies...
    pip install -r requirements.txt --quiet
    if !errorlevel! neq 0 (
        echo [91m[ERROR][0m Failed to install dependencies!
        echo    Try: pip install -r requirements.txt
        pause
        exit /b 1
    )
    echo    [92m[OK][0m All dependencies installed ^(including OpenTelemetry^).
) else (
    echo    [92m[OK][0m All dependencies present.
)

:: ============================================================
:: СОЗДАНИЕ .env ФАЙЛА
:: ============================================================
echo [93m[4/7][0m Checking environment configuration...
if not exist "backend\.env" (
    echo    [93m[WARNING][0m backend\.env not found. Creating template...
    (
        echo # N.I.N.A. AI Cortex - Environment Configuration
        echo # Generated by start_cortex.bat
        echo.
        echo ENVIRONMENT=development
        echo.
        echo # InfluxDB
        echo INFLUXDB_TOKEN=my-super-secret-token
        echo.
        echo # Ollama LLM
        echo OLLAMA_HOST=http://localhost:11434
        echo LLM_PRIMARY_MODEL=gemma4:31b-cloud
        echo LLM_FALLBACK_MODEL=gemma4:e4b
        echo LLM_PRIMARY_TIMEOUT=30.0
        echo LLM_FALLBACK_TIMEOUT=15.0
        echo LLM_MAX_TOKENS=1500
        echo LLM_TEMPERATURE=0.3
        echo LLM_FALLBACK_ENABLED=true
        echo.
        echo # OpenTelemetry ^(Sprint 4^)
        echo OTEL_ENABLED=false
        echo OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
        echo OTEL_SERVICE_NAME=nina-ai-cortex
        echo OTEL_TRACES_SAMPLER_ARG=1.0
        echo OTEL_TRACES_EXPORTER=otlp
    ) > backend\.env
    echo    [92m[OK][0m Template created at backend\.env
    echo    [93m[INFO][0m Edit backend\.env to set your real tokens!
) else (
    echo    [92m[OK][0m backend\.env found.
)

:: ============================================================
:: ПРОВЕРКА DOCKER
:: ============================================================
echo [93m[5/7][0m Checking Docker...
set DOCKER_AVAILABLE=0
where docker >nul 2>&1
if %errorlevel% equ 0 (
    set DOCKER_AVAILABLE=1
    echo    [92m[OK][0m Docker found.
)

if !DOCKER_AVAILABLE! equ 1 (
    echo    Checking if Docker Desktop is running...
    docker info >nul 2>&1
    set DOCKER_RUNNING=!errorlevel!
    if !DOCKER_RUNNING! equ 0 (
        echo    [92m[OK][0m Docker is running. Starting infrastructure...
        
        :: Пробуем новый синтаксис docker compose
        docker compose up -d >nul 2>&1
        set COMPOSE_RESULT=!errorlevel!
        
        :: Если не сработало, пробуем старый синтаксис
        if !COMPOSE_RESULT! neq 0 (
            docker-compose up -d >nul 2>&1
            set COMPOSE_RESULT=!errorlevel!
        )
        
        if !COMPOSE_RESULT! equ 0 (
            echo    [92m[OK][0m Infrastructure started successfully
            echo    [96m       Qdrant: [0mhttp://localhost:6333
            echo    [96m       InfluxDB: [0mhttp://localhost:8086
            echo    [96m       Jaeger UI: [0mhttp://localhost:16686  [93m^(Sprint 4^)[0m
        ) else (
            echo    [91m[WARNING][0m Failed to start containers. Check Docker Desktop.
        )
    ) else (
        echo    [91m[WARNING][0m Docker Desktop is not running.
        echo    Please start Docker Desktop or ensure services are available:
        echo      - Qdrant [96m^(port 6333^)[0m
        echo      - InfluxDB [96m^(port 8086^)[0m
        echo      - Jaeger [96m^(ports 4317, 16686^)[0m  [93m^(Sprint 4^)[0m
    )
) else (
    echo    [91m[WARNING][0m Docker is not installed.
    echo    Make sure external services are running:
    echo      - Qdrant [96m^(port 6333^)[0m
    echo      - InfluxDB [96m^(port 8086^)[0m
    echo      - Jaeger [96m^(ports 4317, 16686^)[0m  [93m^(Sprint 4^)[0m
)

:: ============================================================
:: ПРОВЕРКА OLLAMA
:: ============================================================
echo [93m[6/7][0m Checking Ollama LLM server...
curl -s http://localhost:11434/api/tags >nul 2>&1
if %errorlevel% equ 0 (
    echo    [92m[OK][0m Ollama is running at http://localhost:11434
    
    :: Проверяем наличие моделей
    curl -s http://localhost:11434/api/tags > ollama_models.tmp 2>&1
    findstr /C:"gemma4:31b-cloud" ollama_models.tmp >nul 2>&1
    if !errorlevel! equ 0 (
        echo       [92m✓[0m gemma4:31b-cloud ^(primary^)
    ) else (
        echo       [91m✗[0m gemma4:31b-cloud NOT found
        echo         Install: [96mollama pull gemma4:31b-cloud[0m
    )
    
    findstr /C:"gemma4:e4b" ollama_models.tmp >nul 2>&1
    if !errorlevel! equ 0 (
        echo       [92m✓[0m gemma4:e4b ^(fallback^)
    ) else (
        echo       [93m○[0m gemma4:e4b NOT found ^(optional^)
        echo         Install: [96mollama pull gemma4:e4b[0m
    )
    del ollama_models.tmp >nul 2>&1
) else (
    echo    [91m[WARNING][0m Ollama is not running!
    echo    Start Ollama: [96mollama serve[0m
    echo    Or install from: https://ollama.com
)

:: ============================================================
:: ЗАПУСК FASTAPI СЕРВЕРА
:: ============================================================
echo [93m[7/7][0m Starting FastAPI server...
echo.
echo [96m============================================================[0m
echo [96m  N.I.N.A. AI Cortex is starting...[0m
echo [96m============================================================[0m
echo.
echo  [92m📖 API Documentation:[0m  http://localhost:8000/docs
echo  [92m📊 Prometheus Metrics:[0m http://localhost:8000/metrics
echo  [92m🔌 WebSocket:[0m          ws://localhost:8000/ws
echo.
echo  [96m🔭 Jaeger Tracing UI:[0m  http://localhost:16686  [93m^(if enabled^)[0m
echo  [96m📈 Grafana ^(future^):[0m   http://localhost:3000   [93m^(if configured^)[0m
echo.
echo  [93mPress Ctrl+C to stop the server[0m
echo.
echo [96m============================================================[0m
echo.

:: Переход в backend директорию
cd backend

:: Запуск uvicorn с auto-reload
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

pause